name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build FakeXrmEasy.9.Net -c Release
    - name: Test
      run: dotnet test FakeXrmEasy.Tests.9.Net -c Release
    - name: Pack nugets
      run: nuget pack FakeXrmEasy.9.net.nuspec -prop configuration=release -BasePath FakeXrmEasy.9.Net -version ${{ github.ref_name }}
    - name: Push to NuGet
      run: dotnet nuget push "**/RentReady*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json